<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

return new class extends Migration
{
    public function up(): void
    {
        // 1. Add slug as nullable first so existing rows don't violate NOT NULL
        Schema::table('projects', function (Blueprint $table) {
            $table->string('slug')->nullable()->after('title');
        });

        // 2. Delete the placeholder test record (title="project", description="wertyui")
        DB::table('projects')
            ->where('title', 'project')
            ->where('description', 'wertyui')
            ->delete();

        // 3. Backfill slugs from titles, ensuring uniqueness
        $projects = DB::table('projects')->orderBy('id')->get(['id', 'title']);
        foreach ($projects as $project) {
            $base = Str::slug($project->title);
            $slug = $base;
            $counter = 2;
            while (DB::table('projects')->where('slug', $slug)->where('id', '!=', $project->id)->exists()) {
                $slug = $base . '-' . $counter++;
            }
            DB::table('projects')->where('id', $project->id)->update(['slug' => $slug]);
        }

        // 4. Set placeholder cover images for the 4 real projects
        //    NOTE: These are sample/placeholder images generated by Xynera tooling.
        //    Replace with real project photography before going live.
        $images = [
            'orbit-dashboard'       => 'projects/orbit-dashboard.jpg',
            'puls-finance'          => 'projects/puls-finance.jpg',
            'vanta-studio'          => 'projects/vanta-studio.jpg',
            'nexus-ai-architecture' => 'projects/nexus-ai-architecture.jpg',
        ];
        foreach ($images as $slug => $path) {
            DB::table('projects')->where('slug', $slug)->update(['image_path' => $path]);
        }

        // 5. Now add the unique + not-null constraint
        Schema::table('projects', function (Blueprint $table) {
            $table->string('slug')->nullable(false)->unique()->change();
        });
    }

    public function down(): void
    {
        Schema::table('projects', function (Blueprint $table) {
            $table->dropUnique(['slug']);
            $table->dropColumn('slug');
        });
    }
};
